**ASSIGNMENT 1**

**J THREVIKRAM 21BEC1302**

**VIT CHENNAI**

In [ ]:
import pandas as pd
import numpy as np

**TASK 1**

In [ ]:
np1=np.random.randint(1,50,4)
np1

array([46, 22, 19, 26])

In [ ]:
np2=np.random.randint(50,100,4)
np2

array([72, 51, 62, 79])

In [ ]:
np3=np.random.randint(1,100,4)
np3

array([68, 47, 60, 96])

In [ ]:
np4=np.random.randint(100,200,4)
np4

array([140, 169, 140, 177])

In [ ]:
df=pd.DataFrame([np1,np2,np3,np4])
df

0    1    2    3
0   46   22   19   26
1   72   51   62   79
2   68   47   60   96
3  140  169  140  177

**TASK 2**

In [ ]:
df.columns=['Random value 1','Random value 2','Random value 3','Random value 4']
df

Random value 1  Random value 2  Random value 3  Random value 4
0              46              22              19              26
1              72              51              62              79
2              68              47              60              96
3             140             169             140             177

**TASK 3**

In [ ]:
df.describe()

Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean        81.500000       72.250000       70.250000       94.500000
std         40.640702       65.764099       50.546184       62.559305
min         46.000000       22.000000       19.000000       26.000000
25%         62.500000       40.750000       49.750000       65.750000
50%         70.000000       49.000000       61.000000       87.500000
75%         89.000000       80.500000       81.500000      116.250000
max        140.000000      169.000000      140.000000      177.000000

**TASK 4**

In [ ]:
df.isnull().any()

Random value 1    False
Random value 2    False
Random value 3    False
Random value 4    False
dtype: bool

**TASK 5 - loc method**

In [ ]:
selected_loc = df.loc[:,['Random value 2','Random value 3']]
selected_loc

Random value 2  Random value 3
0              22              19
1              51              62
2              47              60
3             169             140

**TASK 5 - iloc method**

In [ ]:
selected_iloc = df.iloc[:,1:3]
selected_iloc

Random value 2  Random value 3
0              22              19
1              51              62
2              47              60
3             169             140